In [1]:

import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
a = 'i want to go to the cinema and i will show my movie'

In [3]:
b = a.split(' ')
b

['i',
 'want',
 'to',
 'go',
 'to',
 'the',
 'cinema',
 'and',
 'i',
 'will',
 'show',
 'my',
 'movie']

In [4]:
c = {}
for y, i in enumerate(b):
    c[i] = y
print(c)
sentence = [i for i in c.values()]
sentence

{'i': 8, 'want': 1, 'to': 4, 'go': 3, 'the': 5, 'cinema': 6, 'and': 7, 'will': 9, 'show': 10, 'my': 11, 'movie': 12}


[8, 1, 4, 3, 5, 6, 7, 9, 10, 11, 12]

In [5]:
emb_sen = nn.Embedding(20, 16)
emb = emb_sen(torch.LongTensor(sentence)).detach()
emb.shape

torch.Size([11, 16])

In [6]:
emb_w = emb.matmul(emb.T)
emb_w.shape

torch.Size([11, 11])

In [7]:
a_ij = F.softmax(emb_w, dim = 1)
a_ij.shape

torch.Size([11, 11])

In [12]:
a_ij[0].sum()

tensor(1.0000)

In [8]:
z_i = a_ij.matmul(emb)
z_i.shape

torch.Size([11, 16])

In [11]:
z_i[1]

tensor(2.3627)

In [15]:
d = emb.shape[1];d

16

In [21]:
Uq = torch.rand(d,d)
Uk = torch.rand(d,d)
Uv = torch.rand(d,d)

In [23]:
x_2 = emb[1]
x_2

tensor([ 1.7696,  0.5560,  0.2963,  0.0409,  0.0901, -0.3512,  0.1224, -0.1185,
        -0.5733,  0.1369, -0.4763,  1.1752,  0.6687,  0.2212, -0.7250, -0.4840])

In [24]:
query_2 = Uq.matmul(x_2)
key_2 = Uk.matmul(x_2)
value_2 = Uv.matmul(x_2)

In [32]:
keys = Uk.matmul(emb.T).T
values = Uv.matmul(emb.T).T

In [35]:
keys[1]

tensor([ 2.5067,  1.5560,  0.0832,  1.9249,  1.5029,  2.3487,  1.2648,  0.6974,
         1.9802,  1.6032,  1.0658,  0.5467,  0.9956, -0.5706, -0.2534,  1.2489])

In [34]:
key_2

tensor([ 2.5067,  1.5560,  0.0832,  1.9249,  1.5029,  2.3487,  1.2648,  0.6974,
         1.9802,  1.6032,  1.0658,  0.5467,  0.9956, -0.5706, -0.2534,  1.2489])

In [37]:
omega_23 = query_2.matmul(keys[1])
omega_23

tensor(27.5305)

In [38]:
omega_2 = query_2.matmul(keys.T)
omega_2

tensor([  9.6468,  27.5305, -45.8645,  33.8281,  44.2919, -14.9379,  23.3674,
        -13.6761,  16.3823,  69.6213,  -3.6637])

In [44]:
attention = F.softmax(omega_2/d**0.5,dim = 0)
attention.shape

torch.Size([11])

In [45]:
values.shape

torch.Size([11, 16])

In [47]:
context_vector_2 = attention.matmul(values)
context_vector_2


tensor([3.0222, 3.1490, 3.2924, 1.9053, 4.4982, 4.6931, 3.4201, 2.8413, 4.6421,
        3.5703, 4.2608, 4.5087, 4.7197, 3.9792, 4.5155, 6.4491])