In [1]:
import os

import timm
import torch

model = timm.create_model('resnet34')
x     = torch.randn(1, 3, 224, 224)
model(x).shape

torch.Size([1, 1000])

In [2]:
import timm
import torch
import repl
from PIL import Image

In [3]:
model = timm.create_model('resnet34', pretrained=True)

In [4]:
#img = Image.open('./root/images/0.jpg').convert('RGB')
#img

In [5]:
#img.size

In [13]:
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.Resize((224,224)),transforms.ToTensor(),

                                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
                                ])

# define an image dataset

image_dataset = datasets.ImageFolder(root='./root', transform=transform)

In [14]:
image_dataset[0]

(tensor([[[2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          ...,
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489]],
 
         [[2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          ...,
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286]],
 
         [[2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
          [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
          [2.6400, 2.6400, 2.6400,  ...,

In [15]:
# define the dataloader to load that single image
from torch.utils import data
dataloader = data.DataLoader(dataset=image_dataset, shuffle=False, batch_size=8)

In [16]:
next(iter(dataloader))


[tensor([[[[ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489],
           [ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489],
           [ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489],
           ...,
           [ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489],
           [ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489],
           [ 2.2489,  2.2489,  2.2489,  ...,  2.2489,  2.2489,  2.2489]],
 
          [[ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
           [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
           [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
           ...,
           [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
           [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286],
           [ 2.4286,  2.4286,  2.4286,  ...,  2.4286,  2.4286,  2.4286]],
 
          [[ 2.6400,  2.6400,  2.6400,  ...,  2.6400,  2.6400,  2.6400],
           [ 

In [25]:
feature_embeddings = []
from tqdm import tqdm
with torch.no_grad():
    for image, label in tqdm(dataloader):
        embedding = model(image)
        feature_embeddings.extend(embedding)

100%|██████████| 256/256 [01:08<00:00,  3.71it/s]


In [26]:
len(feature_embeddings)

2046

In [27]:
 numpy_embeddings = [tensor_array.numpy() for tensor_array in feature_embeddings]

In [28]:
numpy_embeddings[0].shape

(1000,)

In [29]:
import numpy as np
np_emb = np.vstack(numpy_embeddings)

In [30]:
image_dataset.imgs

[('./root/images/0.jpg', 0),
 ('./root/images/1002.jpg', 0),
 ('./root/images/1005.jpg', 0),
 ('./root/images/1008.jpg', 0),
 ('./root/images/1011.jpg', 0),
 ('./root/images/1014.jpg', 0),
 ('./root/images/1017.jpg', 0),
 ('./root/images/102.jpg', 0),
 ('./root/images/1020.jpg', 0),
 ('./root/images/1023.jpg', 0),
 ('./root/images/1026.jpg', 0),
 ('./root/images/1029.jpg', 0),
 ('./root/images/1032.jpg', 0),
 ('./root/images/1035.jpg', 0),
 ('./root/images/1038.jpg', 0),
 ('./root/images/1041.jpg', 0),
 ('./root/images/1044.jpg', 0),
 ('./root/images/1047.jpg', 0),
 ('./root/images/105.jpg', 0),
 ('./root/images/1050.jpg', 0),
 ('./root/images/1053.jpg', 0),
 ('./root/images/1056.jpg', 0),
 ('./root/images/1059.jpg', 0),
 ('./root/images/1062.jpg', 0),
 ('./root/images/1065.jpg', 0),
 ('./root/images/1068.jpg', 0),
 ('./root/images/1071.jpg', 0),
 ('./root/images/1074.jpg', 0),
 ('./root/images/1077.jpg', 0),
 ('./root/images/108.jpg', 0),
 ('./root/images/1080.jpg', 0),
 ('./root/imag

In [32]:
import pandas as pd
image_filelist = pd.DataFrame(image_dataset.imgs)[0]
print(image_filelist)
pd.DataFrame(np_emb)

0          ./root/images/0.jpg
1       ./root/images/1002.jpg
2       ./root/images/1005.jpg
3       ./root/images/1008.jpg
4       ./root/images/1011.jpg
                 ...          
2041      ./root/images/99.jpg
2042     ./root/images/990.jpg
2043     ./root/images/993.jpg
2044     ./root/images/996.jpg
2045     ./root/images/999.jpg
Name: 0, Length: 2046, dtype: object


0         1         2         3         4         5         6    \
0     0.009128 -0.258768  0.906030  0.885546  0.353621  2.082452  0.900048   
1     0.021291 -0.155517 -1.029944 -0.392221  0.887560 -0.801105 -0.597216   
2     0.196560 -0.275392 -0.677433 -0.076892 -0.716913 -0.471953  0.089809   
3    -1.734549 -0.735825  0.172877  0.121457  0.676266  0.977954  1.127839   
4    -0.070796  0.158393 -0.392704 -1.209007 -0.624599  0.544383 -0.956578   
...        ...       ...       ...       ...       ...       ...       ...   
2041 -0.177438 -0.503833  0.389459 -0.496100  0.024794 -1.406680 -0.834375   
2042  0.605545 -1.129617 -0.950401 -0.295993 -0.631733  0.919994  0.505321   
2043  0.472806 -1.226938 -0.180570 -0.257150  0.542446 -0.252315 -0.017301   
2044 -0.375108  1.079389 -0.513797  0.235272  0.693821 -0.664105 -0.736154   
2045 -0.423011  0.082118  0.398396  0.650823  0.160136  1.086988  1.355408   

           7         8         9    ...       990       991       992  \
0    -1.171227 -0.725601 -1.147103  ...  1.828374 -0.897497  0.362531   
1     0.845133  0.449791  1.178940  ...  0.257904  1.746879 -0.075490   
2     0.559636  0.295080  2.007642  ... -0.169654 -0.036924  0.043583   
3    -0.786345  0.180612 -0.059792  ... -0.742721 -0.862820  0.056144   
4    -0.202349  0.414077 -1.553467  ... -1.051657 -0.339597 -0.623271   
...        ...       ...       ...  ...       ...       ...       ...   
2041  0.611120  0.473136 -1.179701  ...  1.254633  0.573077  0.046071   
2042 -0.005155 -0.081128 -0.820627  ... -0.165525 -0.708621 -0.256763   
2043 -0.298783  0.074320 -0.625084  ... -0.076798 -0.436186 -0.335524   
2044 -0.063929  0.021181  0.505317  ... -0.963240  0.588151 -0.583438   
2045 -0.974790 -0.144399  1.288879  ... -1.299525 -0.596354 -0.186385   

           993       994       995       996       997       998       999  
0    -1.258898  1.646573  0.689821 -1.701383  0.491233 -0.266272  1.169618  
1    -0.174355  0.315248  1.231026  1.788201  1.568237  1.576652 -0.514274  
2    -0.433581 -0.151353 -0.812156  0.784154 -0.716098  0.079135 -0.900364  
3    -0.494988 -0.408080 -0.722059 -1.084637 -1.027896  0.973945 -0.242643  
4    -0.465468 -1.425515  0.814526 -0.113575 -0.646444 -0.379758  0.878057  
...        ...       ...       ...       ...       ...       ...       ...  
2041  0.228973  0.763340 -0.260069  0.488233  0.287987  0.164929 -0.659698  
2042 -1.315068 -0.673670  1.243505 -1.199325  0.580228 -0.535140 -0.420496  
2043  0.183758 -0.854788  0.155274  0.563584 -0.366249  0.344965  0.559003  
2044  0.153053  0.286467  0.221786  0.368910 -0.721660  0.317417  0.907246  
2045 -0.187787 -0.171575 -0.159339  0.157518 -0.339561  0.114189  0.519371  

[2046 rows x 1000 columns]

In [39]:
np.savez('./embeddings.npz', embedding = np_emb, filelist= image_filelist)

In [40]:
dataset = np.load('./embeddings.npz', allow_pickle=True)

In [41]:
dataset.files

['embedding', 'filelist']

In [42]:
dataset['embedding']

array([[ 0.00912803, -0.25876838,  0.90602994, ...,  0.49123323,
        -0.26627243,  1.1696177 ],
       [ 0.02129145, -0.15551698, -1.0299437 , ...,  1.5682373 ,
         1.5766516 , -0.5142735 ],
       [ 0.19656004, -0.27539194, -0.6774335 , ..., -0.7160982 ,
         0.07913453, -0.9003638 ],
       ...,
       [ 0.47280562, -1.2269382 , -0.18056962, ..., -0.3662488 ,
         0.34496453,  0.5590035 ],
       [-0.37510815,  1.0793887 , -0.5137969 , ..., -0.72166   ,
         0.3174172 ,  0.9072465 ],
       [-0.42301095,  0.08211797,  0.39839602, ..., -0.33956146,
         0.11418936,  0.5193708 ]], dtype=float32)

In [43]:
from sklearn.decomposition import PCA

pca = PCA(n_components=16)
pca_embeddings = pca.fit_transform(dataset['embedding'])

In [44]:
from scipy.cluster.vq import kmeans2
centroid, label = kmeans2(pca_embeddings,10, minit = 'points')

In [45]:
label

array([5, 7, 3, ..., 8, 1, 8], dtype=int32)

In [46]:
centroid

array([[-9.943538  , -3.444783  , -3.2353764 , -0.19150956, -2.6320329 ,
         1.1864831 , -0.5782998 , -0.909841  , -0.4444153 , -0.69344157,
        -0.03240251, -0.6656356 , -0.28803185, -0.52492714, -0.3007151 ,
         0.40100163],
       [-2.0967565 , -0.9850636 ,  5.6717005 , -2.462776  ,  0.89416456,
         0.7870207 ,  1.7520456 ,  0.5525641 , -0.08558837, -0.62754494,
        -0.3082773 ,  0.5600372 , -0.5423872 ,  0.549855  ,  0.47841507,
        -0.10468881],
       [10.185325  , -1.8202077 , -3.2737286 , -0.33563462, -2.77764   ,
        -0.4267909 , -1.6254463 ,  1.6824    ,  0.7773259 , -2.5493906 ,
         0.72134066, -0.15452147,  0.09555764,  1.4169027 , -1.4222674 ,
        -0.3105478 ],
       [-3.1266623 , 10.105852  ,  2.5987244 , -1.4952128 , -1.6958619 ,
        -2.5569208 , -2.6084569 , -0.6523305 ,  1.0154732 ,  0.45949623,
         0.436546  , -0.21274374,  1.4631659 , -0.4955795 , -0.247575  ,
        -0.26237062],
       [ 0.5051641 , -6.642111  ,  5

In [47]:
np.bincount(label)

array([294, 280, 155, 204, 150, 207, 160, 218, 218, 160])

In [48]:
import itertools

for label_number in range(10) :
    label_mask = label_number == label
    cluster_images = list(itertools.compress(dataset['filelist'], label_mask))

In [50]:
len(cluster_images)

160

In [58]:
import os
for i in range(10) :
    os.mkdir(f'./output/{i}/')

FileNotFoundError: [Errno 2] No such file or directory: './output/0/'