In [1]:
# First, import PyTorch
import torch
import torch as t

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+t.exp(-x))

In [3]:
### Solution

# Now, make our labels from our data and true weights

y = activation(t.sum(features * weights) + bias)


NameError: name 'features' is not defined

In [4]:
y

NameError: name 'y' is not defined

In [5]:
y = activation((features * weights).sum() + bias)

NameError: name 'features' is not defined

In [33]:
y

tensor([[0.1595]])

In [42]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [43]:
weights.permute(1,0)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [50]:
a = t.mm(features, weights.permute(1,0)) + bias

In [51]:
y = activation(a)

In [52]:
y

tensor([[0.1595]])

In [34]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [35]:
y

tensor([[0.1595]])

In [56]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [60]:
first = activation(t.mm(features, W1)+B1)

In [61]:
second = activation(t.mm(first, W2)+B2)
second

tensor([[0.3171]])

In [62]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.78733187, 0.92798313, 0.82875911],
       [0.27438731, 0.15876574, 0.54481253],
       [0.44824703, 0.6912687 , 0.9082472 ],
       [0.34780732, 0.7325202 , 0.58144905]])

In [63]:
tt = torch.from_numpy(a);tt

tensor([[0.7873, 0.9280, 0.8288],
        [0.2744, 0.1588, 0.5448],
        [0.4482, 0.6913, 0.9082],
        [0.3478, 0.7325, 0.5814]], dtype=torch.float64)

In [64]:
tt.numpy()

array([[0.78733187, 0.92798313, 0.82875911],
       [0.27438731, 0.15876574, 0.54481253],
       [0.44824703, 0.6912687 , 0.9082472 ],
       [0.34780732, 0.7325202 , 0.58144905]])

In [65]:
tt.mul_(2)

tensor([[1.5747, 1.8560, 1.6575],
        [0.5488, 0.3175, 1.0896],
        [0.8965, 1.3825, 1.8165],
        [0.6956, 1.4650, 1.1629]], dtype=torch.float64)

In [66]:
a

array([[1.57466373, 1.85596625, 1.65751821],
       [0.54877461, 0.31753149, 1.08962505],
       [0.89649407, 1.3825374 , 1.8164944 ],
       [0.69561464, 1.46504041, 1.16289809]])